// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gofixcarz/Analytics.tsx": () => import("../components/mockups/gofixcarz/Analytics.tsx"),
  "./components/mockups/gofixcarz/Bookings.tsx": () => import("../components/mockups/gofixcarz/Bookings.tsx"),
  "./components/mockups/gofixcarz/Dashboard.tsx": () => import("../components/mockups/gofixcarz/Dashboard.tsx"),
  "./components/mockups/gofixcarz/Jobs.tsx": () => import("../components/mockups/gofixcarz/Jobs.tsx"),
  "./components/mockups/gofixcarz/Login.tsx": () => import("../components/mockups/gofixcarz/Login.tsx"),
  "./components/mockups/gofixcarz/Profile.tsx": () => import("../components/mockups/gofixcarz/Profile.tsx")
};
